/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/admin/assignmentForm`; params?: Router.UnknownInputParams; } | { pathname: `/admin/assignments`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/subjectForm`; params?: Router.UnknownInputParams; } | { pathname: `/admin/subjects`; params?: Router.UnknownInputParams; } | { pathname: `/admin/uploadNotes`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/user/assignment`; params?: Router.UnknownInputParams; } | { pathname: `/user/home`; params?: Router.UnknownInputParams; } | { pathname: `/user/notes`; params?: Router.UnknownInputParams; } | { pathname: `/user/profile`; params?: Router.UnknownInputParams; } | { pathname: `/note/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/pdf/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/assignmentForm`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/assignments`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/subjectForm`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/subjects`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/uploadNotes`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/users`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/user/assignment`; params?: Router.UnknownOutputParams; } | { pathname: `/user/home`; params?: Router.UnknownOutputParams; } | { pathname: `/user/notes`; params?: Router.UnknownOutputParams; } | { pathname: `/user/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/note/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/pdf/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/analytics${`?${string}` | `#${string}` | ''}` | `/admin/assignmentForm${`?${string}` | `#${string}` | ''}` | `/admin/assignments${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/subjectForm${`?${string}` | `#${string}` | ''}` | `/admin/subjects${`?${string}` | `#${string}` | ''}` | `/admin/uploadNotes${`?${string}` | `#${string}` | ''}` | `/admin/users${`?${string}` | `#${string}` | ''}` | `/auth/signin${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/user/assignment${`?${string}` | `#${string}` | ''}` | `/user/home${`?${string}` | `#${string}` | ''}` | `/user/notes${`?${string}` | `#${string}` | ''}` | `/user/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/admin/assignmentForm`; params?: Router.UnknownInputParams; } | { pathname: `/admin/assignments`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/subjectForm`; params?: Router.UnknownInputParams; } | { pathname: `/admin/subjects`; params?: Router.UnknownInputParams; } | { pathname: `/admin/uploadNotes`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/user/assignment`; params?: Router.UnknownInputParams; } | { pathname: `/user/home`; params?: Router.UnknownInputParams; } | { pathname: `/user/notes`; params?: Router.UnknownInputParams; } | { pathname: `/user/profile`; params?: Router.UnknownInputParams; } | `/note/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/pdf/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/note/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/pdf/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
